 [phases.setup]
nixPkgs = ["python3", "gcc", "libffi", "openssl"]

[phases.install]
commands = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
command = "python bot.py"

[build.environment]
TELEGRAM_BOT_TOKEN = { required = true }
BINANCE_API_KEY = { required = true }
BINANCE_API_SECRET = { required = true }
